### ISSUE TITLE
Program folder organization (no big deal, just suggestion)

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/F95CheckerX#13]
I mentioned this a long time ago to WillyJL too, but he never did anything with it.

When the program updates, it dumps all the managed code libraries in the program root folder, the base F95Checker in the past dumped those in the `Lib` folder, together with the VC Runtimes. Leaving only the two Python libraries within the program root folder.
Both F95Checker and F95CheckerX have no issues if I move them to the `Lib` folder, since that's where the executable looks for them anyway if they aren't within the programs root folder.
It's no big deal, but it does make the program root folder a bit cleaner. 

Something in his build process changed to cause this to happen, and I suspect that it rippled through to your fork, as it also happens in your auto-update.

I'll admit having a bit of OCD, so I always move them there myself. 

Do what you will, thought I'd just mention it

**Comment by littleraisins** [comment]
Unfortunately, we have no control over the paths of `dll`s and shared libraries, they are determined by `cx_Freeze` (exe builder).
They can be "manually" copied when GitHub workflow is executed but it's not worth the risk, since some of them should be on the top level (it can work just fine on your machine but crash on others).

**Comment by FaceCrap** [comment]
Ah, so the `cx_Freeze` is the thing that causes this. That explains why they were included in the `lib` folder in the past, since he added that one later in the life-cycle.
