### ISSUE TITLE
Suggestion: Video support

### ISSUE THREAD

**Issue by Valter4** [littleraisins/F95CheckerX#23]
Would video support be possible? I tried using animated pics, but webps and gifs honestly just eat up unreasonable amounts of RAM. Video is probably a lighter option, but selecting one just shows a black screen. Cheers.

**Comment by FaceCrap** [comment]
videosupport where? and webp? you probably meant webm? and if that already ate up a lot of ram, think what other video formats would do since webm is already oftentimes smaller than the same file encoded in mp4.

**Comment by littleraisins** [comment]
I might be able to do it, but I'm unsure how to integrate videos in the current setup.
Like, if you enabled image cycling and video shows up, should it start playing right away or something more reasonable should happen e.g. showing only the first frame in the carousel and full video on the game popup screen with proper controls and everything?

**Comment by littleraisins** [comment]
I suspect you want them to mimic behaviour of gifs and webms and play constantly on a loop, just with a less ram usage

**Comment by Valter4** [comment]
> I suspect you want them to mimic behaviour of gifs and webms and play constantly on a loop, just with a less ram usage

Correct, autoplay+loop on hover would be The Good Stuff (tm).

**Comment by Willy-JL** [comment]
i can see this becoming a problem since each individual frame needs to be loaded into ram and then copied to vram for imgui to use it, and videos tend to have lots of frames. videos are usually practical due to not storing all frames in their entirety, but only some keyframes along with mathematical interpolation values to describe what changed between keyframes. thats also why gifs are usually so huge compared to videos, they need to store all the frames.

so i foresee 2 possible obstacles:
- interpolating all the frames from a keyframed video, either at:
  - save-time, causing huge stored files, or
  - run-time, causing slow times to load video entities
- ram / vram contraints with these large amounts of frames

let us know how it goes, but i personally would not know what to make of this :D good luck

**Comment by littleraisins** [comment]
> i can see this becoming a problem since each individual frame needs to be loaded into ram and then copied to vram for imgui to use it, and videos tend to have lots of frames

Yeah, I definitely know too little about hardware rendering to optimize existing code. So I was hoping that the `python-mpv` library would help me to offload video rendering tasks to `libmpv`. I've managed to integrate it into current `imagehelper` but overheads are huge, and RAM usage increased instead of decreasing (2x on average).

I'm not abandoning the idea, but I'll focus on other issues for now while doing some research on the topic.

**Comment by littleraisins** [comment]
@Valter4
I gave this one a fair shot, but I'm really out of my depth here.
Even if I could implement an acceptable video support, all the problems described above by Willy would still apply.
Considering how many animated elements are typically on screen in Checker, the performance degradation would be very noticeable if every frame was loaded during run-time. Especially on lower end systems.
