### ISSUE TITLE
Crash after having added images for image cycling.

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/F95CheckerX#7]
Been playing with the image cycling feature, got a crash when I tried a refresh.

![2023-09-20_135136](https://github.com/littleraisins/F95CheckerX/assets/95778718/f6be656d-ac11-4e7e-aaf3-2a6fb6ba377f)
I did not immediately notice this, but there's also a bug related to the default banner image... it gets saved with a double period.
I kept getting this when starting, so had to go into the DB and clear the column where the cycle images were stored. 

And when I re-launched I got this error
![2023-09-20_135221](https://github.com/littleraisins/F95CheckerX/assets/95778718/9b230cf8-257b-4771-9aab-dd4de9b0b7af)

And I suspect the second one is because I copied the images folder from the original without realizing your version makes subfolders

**Comment by FaceCrap** [comment]
This was still in build 20 btw...

**Comment by littleraisins** [comment]
Everything should be fixed in build 32

**Comment by littleraisins** [comment]
To clear things up a little.
You moved images folder from the original and it was the right thing to do.
Old images should be migrated to subfolders automatically and renamed to 'banner.whaterver'

Clearing "attachment_urls" column in DB shouldn't resolve any issues since it's only used to download images, everything else happens in the filesystem, including image ordering.
